### getAllUsers
GET http://localhost:3306/users

### postUserRegistration
POST http://localhost:3306/users
Content-Type: application/json

{
    "name": "Gi", 
    "email": "gi@gi.com", 
    "password": "password"
}

### getAllProducts
GET http://localhost:3306/products?order=asc&search=sel

### postProductRegistration
POST http://localhost:3306/products 
Content-Type: application/json

{
    "name": "Selfie",
    "price": 20,
    "image_url": "https://avatars.githubusercontent.com/u/62773607?s=48&v=4"
}

### getAllPurchases
GET http://localhost:3306/users/1/purchases

### postPurchaseRegistration 
POST http://localhost:3306/purchases 
Content-Type: application/json

{
    "user_id": "2632118f-b9cc-4dd8-a442-8cbf5c0a76fc",
    "product_id": "7186de01-a622-45ae-9104-ffd14e4314b9",
    "quantity": 3
}