###
GET http://localhost:3003/users

###
GET http://localhost:3003/users/admin

###
GET http://localhost:3003/user?name=Alice

###
POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Gi",
    "email": "gi@gi.com",
    "type": "ADMIN",
    "age": "23"
}